[package]
name = "plugin"
version = "0.1.0"
edition = "2018"

[lib]
name = "plugin"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
const-cstr = "0.3.0"

[build-dependencies]
cc = "1.0"
cbindgen = "0.20.0"